import { createServer } from "http";
import { getSnapshots } from "../../history/store.js";
import type { HealthSnapshot } from "../../history/types.js";

function generateHtml(snapshots: HealthSnapshot[], projectName: string): string {
  const data = JSON.stringify(snapshots.map((s) => ({
    date: s.timestamp,
    score: s.metrics.healthScore,
    todos: s.metrics.todoCount,
    deps: s.metrics.outdatedDeps,
    critical: s.metrics.recommendations.critical,
    high: s.metrics.recommendations.high,
    medium: s.metrics.recommendations.medium,
    low: s.metrics.recommendations.low,
    commit: s.commitHash.slice(0, 7),
    branch: s.branch,
  })));

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Beacon Dashboard — ${projectName}</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #0f1117; color: #e1e4e8; padding: 2rem; }
  h1 { font-size: 1.5rem; margin-bottom: 0.5rem; }
  .subtitle { color: #8b949e; margin-bottom: 2rem; }
  .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 1rem; margin-bottom: 2rem; }
  .card { background: #161b22; border: 1px solid #30363d; border-radius: 8px; padding: 1.25rem; }
  .card-label { color: #8b949e; font-size: 0.8rem; text-transform: uppercase; letter-spacing: 0.05em; }
  .card-value { font-size: 2rem; font-weight: 700; margin-top: 0.25rem; }
  .green { color: #3fb950; }
  .yellow { color: #d29922; }
  .red { color: #f85149; }
  .chart-container { background: #161b22; border: 1px solid #30363d; border-radius: 8px; padding: 1.5rem; margin-bottom: 1.5rem; }
  .chart-title { font-size: 1rem; margin-bottom: 1rem; }
  canvas { width: 100% !important; height: 300px !important; }
  table { width: 100%; border-collapse: collapse; margin-top: 1rem; }
  th, td { text-align: left; padding: 0.5rem 1rem; border-bottom: 1px solid #30363d; }
  th { color: #8b949e; font-size: 0.8rem; text-transform: uppercase; }
  .footer { color: #8b949e; font-size: 0.8rem; margin-top: 2rem; text-align: center; }
</style>
<script src="https://cdn.jsdelivr.net/npm/chart.js@4"></script>
</head>
<body>
<h1>Beacon Dashboard</h1>
<p class="subtitle">${projectName} — ${snapshots.length} snapshots</p>

<div class="grid" id="cards"></div>

<div class="chart-container">
  <div class="chart-title">Health Score Over Time</div>
  <canvas id="scoreChart"></canvas>
</div>

<div class="chart-container">
  <div class="chart-title">Issues by Priority</div>
  <canvas id="issuesChart"></canvas>
</div>

<div class="chart-container">
  <div class="chart-title">History</div>
  <table>
    <thead><tr><th>Date</th><th>Commit</th><th>Branch</th><th>Score</th><th>Issues</th><th>TODOs</th></tr></thead>
    <tbody id="historyTable"></tbody>
  </table>
</div>

<div class="footer">Generated by Beacon</div>

<script>
const data = ${data};
const latest = data[data.length - 1];
const prev = data.length > 1 ? data[data.length - 2] : null;

// Cards
const cards = document.getElementById('cards');
function scoreColor(s) { return s >= 80 ? 'green' : s >= 60 ? 'yellow' : 'red'; }
function delta(curr, prev, invert) {
  if (!prev) return '';
  const d = curr - (invert ? prev : prev);
  const arrow = d > 0 ? (invert ? '▼' : '▲') : d < 0 ? (invert ? '▲' : '▼') : '—';
  return ' <span style="font-size:0.8rem;color:#8b949e">' + arrow + ' ' + (d > 0 ? '+' : '') + d + '</span>';
}
const totalIssues = latest.critical + latest.high + latest.medium + latest.low;
cards.innerHTML = [
  { label: 'Health Score', value: latest.score, cls: scoreColor(latest.score) },
  { label: 'Critical Issues', value: latest.critical, cls: latest.critical > 0 ? 'red' : 'green' },
  { label: 'Total Issues', value: totalIssues, cls: totalIssues > 5 ? 'yellow' : 'green' },
  { label: 'TODOs', value: latest.todos, cls: latest.todos > 10 ? 'yellow' : 'green' },
].map(c => '<div class="card"><div class="card-label">' + c.label + '</div><div class="card-value ' + c.cls + '">' + c.value + '</div></div>').join('');

// Score chart
const labels = data.map(d => new Date(d.date).toLocaleDateString());
new Chart(document.getElementById('scoreChart'), {
  type: 'line',
  data: {
    labels,
    datasets: [{
      label: 'Health Score',
      data: data.map(d => d.score),
      borderColor: '#3fb950',
      backgroundColor: 'rgba(63,185,80,0.1)',
      fill: true,
      tension: 0.3,
    }]
  },
  options: {
    scales: { y: { min: 0, max: 100, grid: { color: '#30363d' } }, x: { grid: { color: '#30363d' } } },
    plugins: { legend: { display: false } },
  }
});

// Issues chart
new Chart(document.getElementById('issuesChart'), {
  type: 'bar',
  data: {
    labels,
    datasets: [
      { label: 'Critical', data: data.map(d => d.critical), backgroundColor: '#f85149' },
      { label: 'High', data: data.map(d => d.high), backgroundColor: '#d29922' },
      { label: 'Medium', data: data.map(d => d.medium), backgroundColor: '#58a6ff' },
      { label: 'Low', data: data.map(d => d.low), backgroundColor: '#8b949e' },
    ]
  },
  options: {
    scales: { y: { stacked: true, grid: { color: '#30363d' } }, x: { stacked: true, grid: { color: '#30363d' } } },
  }
});

// History table
const tbody = document.getElementById('historyTable');
tbody.innerHTML = [...data].reverse().map(d => {
  const issues = d.critical + d.high + d.medium + d.low;
  const cls = scoreColor(d.score);
  return '<tr><td>' + new Date(d.date).toLocaleDateString() + '</td><td><code>' + d.commit + '</code></td><td>' + d.branch + '</td><td class="' + cls + '">' + d.score + '</td><td>' + issues + '</td><td>' + d.todos + '</td></tr>';
}).join('');
</script>
</body>
</html>`;
}

export async function dashboardCommand(options: {
  port?: number;
}): Promise<void> {
  const port = options.port ?? 3737;
  const snapshots = await getSnapshots();

  if (snapshots.length === 0) {
    console.log("No history data yet. Run 'beacon analyze' to start tracking.");
    return;
  }

  // Get project name from latest snapshot or cwd
  const projectName = process.cwd().split("/").pop() ?? "Project";
  const html = generateHtml(snapshots, projectName);

  const server = createServer((req, res) => {
    res.writeHead(200, { "Content-Type": "text/html" });
    res.end(html);
  });

  server.listen(port, () => {
    const url = `http://localhost:${port}`;
    console.log(`\nBeacon Dashboard running at ${url}`);
    console.log("Press Ctrl+C to stop.\n");

    // Try to open browser
    try {
      const { execSync } = require("child_process");
      const cmd = process.platform === "darwin" ? "open" : process.platform === "win32" ? "start" : "xdg-open";
      execSync(`${cmd} ${url}`, { stdio: "ignore" });
    } catch {
      // Browser open failed — user can navigate manually
    }
  });
}
