import chalk from "chalk";
import { loadConfig, resolveApiKey } from "../../config/loader.js";
import { ContextBuilder } from "../../context/builder.js";
import { createProvider } from "../../analyzer/index.js";
import { getCache, setCache } from "../../cache/index.js";
import { execSync } from "child_process";
import { createSpinner } from "../spinner.js";
import { handleCliError } from "../errors.js";
import { buildSnapshot, recordSnapshot, getCurrentBranch, getSnapshots } from "../../history/store.js";
import type { AnalysisResult } from "../../analyzer/types.js";
import type { ProjectContext } from "../../context/types.js";

function getHeadCommit(): string | null {
  try {
    return execSync("git rev-parse HEAD", { encoding: "utf-8" }).trim();
  } catch {
    return null;
  }
}

function renderReport(
  result: AnalysisResult,
  context: ProjectContext,
  healthScore: number,
  scoreTrend?: { delta: number; days: number }
): string {
  const lines: string[] = [];
  const now = new Date();
  const dateStr = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}-${String(now.getDate()).padStart(2, "0")}`;

  lines.push(chalk.bold(`\n═══════════════════════════════════════`));
  lines.push(chalk.bold(`  Project Health Report — ${dateStr}`));
  lines.push(chalk.bold(`  ${context.project.name}`));
  lines.push(chalk.bold(`═══════════════════════════════════════\n`));

  // Health Score
  const scoreColor = healthScore >= 80 ? chalk.green : healthScore >= 60 ? chalk.yellow : chalk.red;
  let scoreLine = `  Health Score: ${scoreColor(chalk.bold(String(healthScore) + "/100"))}`;
  if (scoreTrend) {
    const trendIcon = scoreTrend.delta > 0 ? chalk.green("▲") : scoreTrend.delta < 0 ? chalk.red("▼") : chalk.gray("—");
    scoreLine += `  ${trendIcon} ${scoreTrend.delta > 0 ? "+" : ""}${scoreTrend.delta} from ${scoreTrend.days}d ago`;
  }
  lines.push(scoreLine);
  lines.push("");

  // Executive summary
  lines.push(chalk.bold("  Summary"));
  lines.push(`  ${result.summary}`);
  lines.push("");

  // Key metrics
  lines.push(chalk.bold("  Key Metrics"));
  lines.push(`  Tech Stack:      ${context.project.techStack.join(", ")}`);
  lines.push(`  Open TODOs:      ${context.health.todos.length}`);
  lines.push(`  Outdated Deps:   ${context.health.outdatedDeps.filter((d) => d.isOutdated).length}`);
  if (context.health.vulnerabilities) {
    const v = context.health.vulnerabilities;
    const vulnColor = v.total > 0 ? chalk.red : chalk.green;
    lines.push(`  Vulnerabilities: ${vulnColor(String(v.total))} (${v.critical} critical, ${v.high} high)`);
  }
  lines.push("");

  // Top priorities (simplified for non-devs)
  const criticalAndHigh = result.recommendations.filter(
    (r) => r.priority === "critical" || r.priority === "high"
  );

  if (criticalAndHigh.length > 0) {
    lines.push(chalk.bold("  Action Items"));
    for (const r of criticalAndHigh.slice(0, 5)) {
      const emoji = r.priority === "critical" ? "🔴" : "🟠";
      lines.push(`  ${emoji} ${r.title}`);
      lines.push(chalk.gray(`     ${r.description}`));
    }
    lines.push("");
  }

  // Risk assessment
  const criticalCount = result.recommendations.filter((r) => r.priority === "critical").length;
  lines.push(chalk.bold("  Risk Level"));
  if (criticalCount > 0) {
    lines.push(chalk.red(`  ⚠ HIGH — ${criticalCount} critical issue(s) require immediate attention`));
  } else if (healthScore < 60) {
    lines.push(chalk.yellow(`  ⚠ MODERATE — Health score below recommended threshold`));
  } else {
    lines.push(chalk.green(`  ✔ LOW — Project is in good health`));
  }
  lines.push("");

  lines.push(chalk.gray(`  Generated by Beacon v${getVersion()}`));
  lines.push("");

  return lines.join("\n");
}

function getVersion(): string {
  try {
    const pkg = JSON.parse(
      execSync("cat package.json", { encoding: "utf-8" })
    );
    return pkg.version ?? "unknown";
  } catch {
    return "unknown";
  }
}

export async function reportCommand(options: {
  json?: boolean;
  verbose?: boolean;
  noCache?: boolean;
}): Promise<void> {
  const projectPath = process.cwd();
  const verbose = options.verbose ?? false;
  const isJson = options.json ?? false;
  const log = (msg: string) => {
    if (verbose) console.error(`[verbose] ${msg}`);
  };

  try {
    const config = await loadConfig(projectPath);
    const apiKey = await resolveApiKey(config.llm.provider, config.llm.apiKey);

    if (!apiKey) {
      console.error(`No API key found for ${config.llm.provider}. Run 'beacon login' to set up your provider.`);
      process.exit(1);
    }

    const spinner = !isJson ? createSpinner() : null;

    spinner?.start("Collecting project data...");
    const builder = new ContextBuilder(config);
    const context = await builder.build(projectPath, verbose);
    spinner?.succeed("Project data collected");

    const commitHash = getHeadCommit();
    const useCache = !(options.noCache ?? false);

    // Check cache first
    let result: AnalysisResult;
    if (useCache && commitHash) {
      const cached = await getCache(commitHash, "analyze");
      if (cached) {
        log("Cache hit!");
        result = cached;
      } else {
        const provider = createProvider(config.llm.provider, apiKey, config.llm.model);
        spinner?.start("Generating report...");
        result = await provider.analyze(context, "analyze", config.language);
        spinner?.succeed("Report ready");
        await setCache(commitHash, "analyze", result);
      }
    } else {
      const provider = createProvider(config.llm.provider, apiKey, config.llm.model);
      spinner?.start("Generating report...");
      result = await provider.analyze(context, "analyze", config.language);
      spinner?.succeed("Report ready");
    }

    const snapshot = buildSnapshot(context, result, commitHash ?? "unknown", getCurrentBranch());

    if (commitHash) {
      await recordSnapshot(snapshot);
    }

    // Calculate trend if history exists
    const snapshots = await getSnapshots();
    let scoreTrend: { delta: number; days: number } | undefined;
    if (snapshots.length >= 2) {
      const oldest = snapshots[0];
      const days = Math.max(
        1,
        Math.round(
          (new Date().getTime() - new Date(oldest.timestamp).getTime()) / 86400000
        )
      );
      scoreTrend = {
        delta: snapshot.metrics.healthScore - oldest.metrics.healthScore,
        days,
      };
    }

    if (isJson) {
      console.log(
        JSON.stringify({
          date: new Date().toISOString(),
          project: context.project.name,
          healthScore: snapshot.metrics.healthScore,
          scoreTrend,
          summary: result.summary,
          riskLevel:
            result.recommendations.filter((r) => r.priority === "critical").length > 0
              ? "high"
              : snapshot.metrics.healthScore < 60
              ? "moderate"
              : "low",
          actionItems: result.recommendations
            .filter((r) => r.priority === "critical" || r.priority === "high")
            .map((r) => ({ priority: r.priority, title: r.title, description: r.description })),
          metrics: snapshot.metrics,
        }, null, 2)
      );
      return;
    }

    console.log(renderReport(result, context, snapshot.metrics.healthScore, scoreTrend));
  } catch (error) {
    handleCliError(error, verbose);
  }
}
